# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e0687cc4508e8efd76e8ff2aa2db43cb04bfd50f769482e6819dbbda4c25ec96bbf10f05bee8881dcfcb3ac554aa572ede19d8d877b963a1a6c3adf7a962779

test:
  secret_key_base: 6f4c53bc5cadd547ac387aa683c2e7cee8127485b7db1574d9d3e8221f6c36b17fbf5d982fab2e335e00645982da5ef1789c442dd26bb39d296ce5b808c5e596

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
